version: '2'
services:
  broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "8883:8883"
  dpa:
    ports:
      - "8319:8319"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./docker-conf:/config:ro
    depends_on:
      - broker
    links:
      - broker