version: '2'
services:
  broker:
    image: eclipse-mosquitto
#    ports:
#      - "1883:1883"
#      - "8883:8883"
  dpa:
    ports:
      - "8319:8319"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./docker-conf:/config:ro
      - ./extra-dependencies:/dependencies:ro
    environment:
      #- "JAVA_OPTS=-Dconnection.broker.mqtt.hostname=magna;env.var.enabled"
       - "connection.broker.mqtt.hostname=magna"
       - "env.var.enabled=true"
    depends_on:
      - broker
    links:
      - broker