version: '2'
services:
#  mqtt-broker:
#    image: eclipse-mosquitto
  dpa:
    ports:
      - "8319:8319"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./docker-conf:/config:ro
    extra_hosts:
       - "broker:129.26.162.113"
 #   depends_on:
 #     - mqtt-broker
 #   links:
 #     - mqtt-broker